### Euler Prject Problem 1
##If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
##The sum of these multiples is 23.
##Find the sum of all the multiples of 3 or 5 below 1000.

#load library
source('C:/Users/Tony Leguia/Desktop/projectEuler/eulerLibrary.R')

# solve problem by running eulerProb1(1000)
eulerProb1 <- function(num){
  sum = 0;
  for(n in 1:num-1){
    if(isMultiple3(n)||isMultiple5(n)){
      sum = sum + n;
    }
  }
  sum;
}

#Test for Euler Problem 1
testProb1 <- function(){
  print(c("Is eulerProb1(10)==23? ", 23==eulerProb1(10)));
  print(c("Is eulerProb1(1000)==233168? ", 233168==eulerProb1(1000)));
}

### Euler Project Problem 2
##Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
##By starting with 1 and 2, the first 10 terms will be:
##    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

##By considering the terms in the Fibonacci sequence whose values do not exceed 
##four million, find the sum of the even-valued terms.

eulerProb2 <- function(num){
  fibSeq <- fibonacci(num);
  sum = sum(fibSeq[fibSeq%%2==0&fibSeq<4000000])
  sum
}

testProb2 <- function(){
  print(c("Is eulerProb1(1000000)==4613732? ", 4613732==eulerProb2(800)));
}